### ISSUE TITLE
训练效果不好

### ISSUE THREAD

**Issue by zrk2002** [riversky2025/SIRLUT#1]
作者你好，我按照readme的步骤在FiveK-sRGB数据集上进行了训练，但是训练出来的效果不好，PSNR最高才24.94，请问可能是哪里出了问题？另外，请问你能分享一下训练好的模型吗？
![image](https://github.com/user-attachments/assets/54c206cb-2cc0-475b-8af3-59a6c9959a39)

**Comment by riversky2025** [comment]
非常感谢您的关注。稍后我们会更新发布训练好的模型。可以备注上您的邮箱，届时给您发送。

**Comment by zrk2002** [comment]
> 非常感谢您的关注。稍后我们会更新发布训练好的模型。可以备注上您的邮箱，届时给您发送。

感谢，我的邮箱是1323268276@sjtu.edu.cn

**Comment by riversky2025** [comment]
非常抱歉，之前代码有部分bug。已经修复。
![image](https://github.com/user-attachments/assets/d3ee7dfa-b702-48bb-b068-b9e6f815283e)

**Comment by aviadmx** [comment]
作者你好，你能分享一下训练好的权重给我吗？我的邮箱是aviad 10 m @ gmail.com（去掉空格）

**Comment by aviadmx** [comment]
作者你好，你能分享一下训练好的权重给我吗？我的邮箱是aviad 10 m @ gmail.com（去掉空格）

**Comment by riversky2025** [comment]
FiveK-sRGB的么？
邮件已经回复。
